### ISSUE TITLE
Simple example of hooking up a smart-table to a meteor collection.

### ISSUE THREAD

**Issue by pnunn** [davidyaha/meteor-smart-table#2]
Hi David,

knowing nothing about Angular I'm having trouble working out how to hook up a smart-table to a collection in meteor. Any simple examples you can point me in the direction of?

Ta

**Comment by davidyaha** [comment]
Hi Peter,

First of all you should really try going to the angular-meteor site here: http://angular-meteor.com, and go through the tutorial over there. One of the things that you will learn there is that after your using $scope.$meteorCollection to bind your collection to the scope, the collection itself gets the properties of a normal array (it is an extended array actually) and therefore could be passed to smart-table as specified in the smart-table docs: http://lorenzofox3.github.io/smart-table-website/

Have fun!
